apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-airflow
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/opt/airflow/dags"

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-logs
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/opt/airflow/logs"